// AUTO-GENERATED by tools/gen_reports.py from hid_descriptor.h.
// Do not edit by hand -- re-run the generator after changing the descriptor.
#ifndef MH_REPORTS_H_
#define MH_REPORTS_H_
#include <stdint.h>

typedef struct {
  uint8_t id;        // Report ID
  uint8_t in_len;    // INPUT report size in bytes (0 = no input / cannot send)
  uint8_t out_len;   // OUTPUT report size in bytes
  uint8_t feat_len;  // FEATURE report size in bytes
} mh_report_info_t;

#define MH_REPORT_COUNT 35

static const mh_report_info_t MH_REPORTS[MH_REPORT_COUNT] = {
  {   1,   5,   0,   0 },  // 0x01 REPORT_ID_GENERIC_DESKTOP
  {   2,  11,   0,   0 },  // 0x02 REPORT_ID_SIMULATION
  {   3,   7,   0,   0 },  // 0x03 REPORT_ID_VR
  {   4,   8,   0,   0 },  // 0x04 REPORT_ID_SPORT
  {   5,   6,   0,   0 },  // 0x05 REPORT_ID_GAME
  {   6,   4,   0,   4 },  // 0x06 REPORT_ID_GENERIC_DEVICE
  {   7,   8,   1,   0 },  // 0x07 REPORT_ID_KEYBOARD
  {   8,   0,   4,   0 },  // 0x08 REPORT_ID_LED
  {   9,   1,   0,   0 },  // 0x09 REPORT_ID_BUTTON
  {  10,   4,   0,   0 },  // 0x0A REPORT_ID_ORDINAL
  {  11,   2,   1,   0 },  // 0x0B REPORT_ID_TELEPHONY
  {  12,   2,   0,   0 },  // 0x0C REPORT_ID_CONSUMER
  {  13,   9,   0,   1 },  // 0x0D REPORT_ID_DIGITIZER
  {  14,   0,   2,   2 },  // 0x0E REPORT_ID_HAPTICS
  {  15,   0,   4,   0 },  // 0x0F REPORT_ID_PID
  {  16,  12,   0,   0 },  // 0x10 REPORT_ID_UNICODE
  {  17,   0,   0,  41 },  // 0x11 REPORT_ID_SOC
  {  18,   8,   0,   0 },  // 0x12 REPORT_ID_EYE_HEAD_TRACKER
  {  19,   0,  16,   2 },  // 0x14 REPORT_ID_AUX_DISPLAY
  {  20,   7,   0,   4 },  // 0x20 REPORT_ID_SENSOR
  {  21,   5,   0,   0 },  // 0x40 REPORT_ID_MEDICAL
  {  22,   1,   8,   1 },  // 0x41 REPORT_ID_BRAILLE
  {  23,   0,   6,  14 },  // 0x59 REPORT_ID_LIGHTING
  {  24,   0,   0, 130 },  // 0x80 REPORT_ID_MONITOR
  {  25,   0,   0,   1 },  // 0x81 REPORT_ID_MONITOR_ENUM
  {  26,   0,   1,  10 },  // 0x82 REPORT_ID_VESA_VC
  {  27,   8,   1,   0 },  // 0x84 REPORT_ID_POWER
  {  28,  10,   0,   0 },  // 0x85 REPORT_ID_BATTERY
  {  29,  33,   1,   1 },  // 0x8C REPORT_ID_BARCODE
  {  30,   6,   1,   0 },  // 0x8D REPORT_ID_SCALE
  {  31, 229,   0,   0 },  // 0x8E REPORT_ID_MSR
  {  32,   1,   0,   0 },  // 0x90 REPORT_ID_CAMERA
  {  33,   2,   2,   0 },  // 0x91 REPORT_ID_ARCADE
  {  34,   8,   8,   0 },  // 0x92 REPORT_ID_GAMING_DEVICE
  {  35,  64,  64,   0 },  // 0xF1D0 REPORT_ID_FIDO
};

#endif // MH_REPORTS_H_
